### Diamond

#### Exercise 1

Read in the diamond dataset found in `diamonds.csv`.

In [51]:
# Put your code here

#### Exercise 2

Filter the dataset so that the resulting dataset only includes information about **color**, **clarity**, and **price** for **premium** diamonds. Show just the first 5 rows for the resulting data frame.

In [52]:
# Put your code here

   color clarity  price
1      E     SI1    326
3      I     VS2    334
12     F     SI1    342
14     E     SI2    345
15     E      I1    345

#### Exercise 3

You are interested in computing a new variable called **box_volume** (bv). This is computed using the following equation:

$$
bv = x*y*z
$$

where $x$, $y$, and $z$ are the dimensions of the diamond given in the dataset (labeled `x`, `y`, and `z`).

Compute this new variable and save it in the data frame as `bv`.

Finally, compute the average box volume.

In [53]:
# Put your code here

np.float64(129.84940333672597)

#### Exercise 4

Rename the categories found in `cut` using the following pattern:

- "Fair" -> 0
- "Good" -> 1
- "Very Good" -> 2
- "Premium" -> 3
- "Ideal" -> 4

Then sort the data frame in descending order of this new `cut` variable. Just show the first 5 rows.

In [54]:
# Put your code here

,carat,cut,color,clarity,depth,table,x,y,z,price,bv
11,0.23,4,J,VS1,62.8,56.0,3.93,3.90,2.46,340,37.704420
53939,0.75,4,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,124.568444
0,0.23,4,E,SI2,61.5,55.0,3.95,3.98,2.43,326,38.202030
13,0.31,4,J,SI2,62.2,54.0,4.35,4.37,2.71,344,51.515745
53919,0.76,4,I,VVS1,62.2,55.0,5.89,5.87,3.66,2753,126.541938

#### Exercise 5

Use the `map` function to create a new variable called `log_carat` which is computed by taking the natural logarithm of `caret`. (You will need to use the `log` function from the `numpy` library). Then compute the mean of `log_carat`.

In [57]:
# Put your code here

np.float64(-0.39496696554823124)

#### Exercise 6

Use the `apply` function to create a new indicator variable called `high_quality` which is `True` when the cut is very good (2) or above and the clarity is either VVS1 or VVS2. Then get the counts for each category of `high_quality`.

In [46]:
# Put your code here

high_quality
False    45777
True      8163
Name: count, dtype: int64

#### Exercise 7

Create a two-way table of color and clarity.

In [48]:
# Put your code here

clarity   I1   IF   SI1   SI2   VS1   VS2  VVS1  VVS2
color
D         42   73  2083  1370   705  1697   252   553
E        102  158  2426  1713  1281  2470   656   991
F        143  385  2131  1609  1364  2201   734   975
G        150  681  1976  1548  2148  2347   999  1443
H        162  299  2275  1563  1169  1643   585   608
I         92  143  1424   912   962  1169   355   365
J         50   51   750   479   542   731    74   131

#### Exercise 8

Look at all correlations between the following variables: `log_caret`, `depth`, `table`, `bv`, and `price`

In [60]:
# Put your code here

           log_carat     depth     table        bv     price
log_carat   1.000000  0.030434  0.191741  0.933977  0.855526
depth       0.030434  1.000000 -0.295779  0.009157 -0.010647
table       0.191741 -0.295779  1.000000  0.167400  0.127134
bv          0.933977  0.009157  0.167400  1.000000  0.902385
price       0.855526 -0.010647  0.127134  0.902385  1.000000

#### Exercise 9

Get the average caret and median price for each cut category.

In [61]:
# Put your code here

        carat   price
cut
0    1.046137  3282.0
1    0.849185  3050.5
2    0.806381  2648.0
3    0.891955  3185.0
4    0.702837  1810.0