### NYC Food

#### Part 1

Using the food delivery dataset, complete the following tasks:

1. **Create a new column** called `total_time` that equals the sum of `food_preparation_time` and `delivery_time`.

2. **Filter the dataset** to only include orders placed on the **Weekend**.

3. **Sort the filtered results** by `cost_of_the_order` in **descending order**.

4. Display the **top 5 most expensive weekend orders**.

In [56]:
import pandas as pd

df = pd.read_csv("nyc_food.csv")

df["total_time"] = df["food_preparation_time"] + df["delivery_time"]

df[df["day_of_the_week"] == "Weekend"].sort_values(by="cost_of_the_order",
                                                  ascending=False).head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time,total_time
1831,1476970,275689,Nobu Next Door,Japanese,33.37,Weekend,4,32,21,53
41,1478143,337525,TAO,Japanese,33.22,Weekend,Not given,23,19,42
1213,1476695,68300,Blue Ribbon Fried Chicken,American,33.18,Weekend,Not given,26,20,46
909,1477183,127934,Blue Ribbon Fried Chicken,American,33.03,Weekend,5,35,25,60
61,1478327,68551,Blue Ribbon Sushi Bar & Grill,Japanese,33.03,Weekend,Not given,33,20,53

#### Part 2

Using the food delivery dataset, complete the following tasks:

1. Create a new column called `is_cheap_and_fast` using **`apply()` and a lambda function**.
   - An order should be labeled **1** if the `cost_of_the_order` is **less than 25** **and** the `total_time` is **less than 40**.
   - Otherwise label it **0**.

2. Group the data by `cuisine_type`.

3. For each cuisine type, calculate:
   - the **average cost of the order**
   - the **total number of cheap and fast orders**

In [57]:
df["is_cheap_and_fast"] = df.apply(lambda row:
                                   1 if (row["cost_of_the_order"] < 25 and row["total_time"] < 40) else 0,
                                   axis = 1)

df.groupby("cuisine_type").agg({"cost_of_the_order": "mean",
                               "is_cheap_and_fast": "sum"})

                cost_of_the_order  is_cheap_and_fast
cuisine_type
American                16.319829                 20
Chinese                 16.305209                 13
French                  19.793889                  0
Indian                  16.919726                  2
Italian                 16.418691                 10
Japanese                16.304532                 14
Korean                  14.001538                  1
Mediterranean           15.474783                  3
Mexican                 16.933117                  2
Middle Eastern          18.820612                  4
Southern                19.300588                  0
Spanish                 18.994167                  1
Thai                    19.207895                  2
Vietnamese              12.882857                  0

In [58]:
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time,total_time,is_cheap_and_fast
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20,45,0
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23,48,0
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28,51,0
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15,40,0
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24,49,0