## Introduction to Pandas

**Pandas** is one of the most widely used Python libraries for **data analysis and data manipulation**. It provides powerful tools that make it easier to work with structured data such as tables, spreadsheets, or CSV files.

---

### Why Pandas?

Real-world datasets are often:
- Large
- Messy
- Stored in files like CSV or Excel
- Organized in rows and columns

Pandas helps us **load, clean, explore, and analyze this data efficiently**.

---

## Reading Data with Pandas

Before we can analyze data, we first need to **load it into Python**.  
Pandas makes it easy to read data from many common file formats.

Most of the time, we will load data into a **DataFrame**.

---

### Step 1: Import Pandas

First, import the pandas library.

```python
import pandas as pd
```

In [1]:
import pandas as pd

stress = pd.read_csv("../data/smartphone_stress.csv")

## Inspecting Pandas DataFrame

Once a dataset has been loaded into a pandas **DataFrame**, several built-in attributes and methods can help you quickly understand its structure and contents.

| Method / Attribute | Description |
|---|---|
| `head()` | Displays the first few rows of the DataFrame (5 by default). Useful for quickly previewing the dataset. |
| `tail()` | Displays the last few rows of the DataFrame (5 by default). Helpful for checking the end of the dataset. |
| `shape` | Returns the dimensions of the DataFrame as a tuple `(rows, columns)`. |
| `columns` | Returns the names of all columns in the DataFrame. |
| `info()` | Provides a summary of the DataFrame including column names, data types, number of non-null values, and memory usage. |
| `describe()` | Generates summary statistics (count, mean, standard deviation, min, quartiles, max) for numerical columns. |

In [2]:
stress.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

In [3]:
stress.tail()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
49995,U49996,44,Male,Business Owner,Android,5.9,5.4,5,6.6,1,11,5,3.0
49996,U49997,42,Other,Business Owner,Android,2.9,7.4,9,6.3,2,20,4,6.2
49997,U49998,27,Female,Freelancer,iOS,1.4,2.5,4,6.7,9,39,4,5.1
49998,U49999,41,Female,Business Owner,iOS,8.9,3.0,6,5.5,2,51,0,9.2
49999,U50000,46,Other,Freelancer,Android,8.8,2.8,3,5.4,1,54,5,6.9

In [4]:
stress.shape

(50000, 13)

In [5]:
stress.columns

Index(['User_ID', 'Age', 'Gender', 'Occupation', 'Device_Type',
       'Daily_Phone_Hours', 'Social_Media_Hours', 'Work_Productivity_Score',
       'Sleep_Hours', 'Stress_Level', 'App_Usage_Count',
       'Caffeine_Intake_Cups', 'Weekend_Screen_Time_Hours'],
      dtype='str')

In [6]:
stress.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  str
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  str
 3   Occupation                 50000 non-null  str
 4   Device_Type                50000 non-null  str
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
dtypes: float64(4), int64(5), str(4)
memory usage: 5.0 MB

In [7]:
stress.describe()

,Age,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,39.034960,6.509116,4.267250,5.503760,6.497744,5.504500,32.43898,3.004580,8.006844
std,12.414877,3.170903,2.164743,2.874806,1.449551,2.871095,16.12151,1.996657,3.461300
min,18.000000,1.000000,0.500000,1.000000,4.000000,1.000000,5.00000,0.000000,2.000000
25%,28.000000,3.800000,2.400000,3.000000,5.200000,3.000000,18.00000,1.000000,5.000000
50%,39.000000,6.500000,4.300000,5.500000,6.500000,6.000000,32.00000,3.000000,8.000000
75%,50.000000,9.200000,6.100000,8.000000,7.800000,8.000000,46.00000,5.000000,11.000000
max,60.000000,12.000000,8.000000,10.000000,9.000000,10.000000,60.00000,6.000000,14.000000

## Selecting and Creating Columns in Pandas

In pandas, columns in a DataFrame can be **selected, modified, or created** using simple indexing operations. This allows you to focus on specific variables or generate new ones from existing data.

You can select and create columns using **square bracket notation**.

```python
df["column_name"] # selects a single column
df[["column_name_1", "column_name_2"]] # selects multiple columns
df["new_column_name"] = new_column_values # creates new column with values in new_column_values 
```

In [8]:
stress["Age"].head()

0    58
1    25
2    19
3    35
4    33
Name: Age, dtype: int64

In [9]:
stress[["Daily_Phone_Hours", "Social_Media_Hours"]].head()

   Daily_Phone_Hours  Social_Media_Hours
0                1.3                 6.7
1                1.2                 1.5
2                5.3                 5.7
3                5.8                 2.5
4                7.9                 1.3

In [10]:
stress["Sleep_Stress_Ratio"] = stress["Sleep_Hours"]/stress["Stress_Level"]
stress[["Sleep_Hours", "Stress_Level", "Sleep_Stress_Ratio"]].head()

   Sleep_Hours  Stress_Level  Sleep_Stress_Ratio
0          8.8             4                2.20
1          6.4             1                6.40
2          9.0             4                2.25
3          5.7             3                1.90
4          5.7             3                1.90

## Filtering Rows in a Pandas DataFrame

Often we only want to work with **rows that meet certain conditions**.  
In pandas, this is done using **Boolean filtering** (also called Boolean indexing).

We create a **condition** that evaluates to `True` or `False` for each row.

In [11]:
stress[stress["App_Usage_Count"] > 10].head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Sleep_Stress_Ratio
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7,2.20
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1,6.40
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,2.25
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8,1.90
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9,1.90

In [12]:
stress[(stress["Caffeine_Intake_Cups"] > 3) & (stress["Age"] < 30)].head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Sleep_Stress_Ratio
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,2.2500
7,U8,24,Male,Freelancer,iOS,8.5,1.9,4,7.8,3,6,6,12.8,2.6000
12,U13,20,Female,Business Owner,iOS,11.1,5.6,3,5.0,4,22,6,4.2,1.2500
13,U14,19,Female,Freelancer,iOS,9.7,4.1,10,6.0,1,36,6,2.3,6.0000
14,U15,23,Male,Professional,Android,1.1,2.5,3,5.3,8,29,5,9.2,0.6625

## Selecting Data in Pandas with `loc` and `iloc`

In pandas, the two most common ways to select rows and columns from a DataFrame are **`loc`** and **`iloc`**. Both are used for indexing, but they work in different ways:

- **`loc` → label-based indexing**
- **`iloc` → integer position-based indexing**

Understanding the difference is essential for reliable data manipulation.

In [77]:
stress.index = stress["User_ID"]
stress.loc[["U1", "U3", "U5"]]
stress.iloc[[0, 2, 4]]
stress.loc[["U1", "U3", "U5"], ["Age", "Gender"]]
stress.iloc[[0, 2, 4], [1, 2]]

         Age Gender
User_ID
U1        58   Male
U3        19   Male
U5        33   Male

## Grouping and Aggregating Data with `groupby`

In many data analysis tasks, we want to **summarize data by categories**.  
For example, we might want to compute:

- The average GPA by major
- The total sales by region
- The number of students in each class year

In pandas, this is done using the **`groupby()`** method combined with **aggregation functions**.

In [13]:
stress.groupby("Gender")["Social_Media_Hours"].mean()

Gender
Female    4.281726
Male      4.246505
Other     4.273581
Name: Social_Media_Hours, dtype: float64

In [14]:
stress.groupby("Occupation")[["Stress_Level", "Sleep_Hours"]].agg(["mean", "median"])

               Stress_Level        Sleep_Hours
                       mean median        mean median
Occupation
Business Owner     5.474356    5.0    6.485264    6.5
Freelancer         5.493344    5.0    6.487132    6.5
Professional       5.504632    6.0    6.518362    6.5
Student            5.545418    6.0    6.499872    6.5

## Sorting Data in a Pandas DataFrame

Sometimes we want to **reorder rows** in a dataset based on the values in one or more columns.  
In pandas, this is done using the **`sort_values()`** method.

In [15]:
stress.sort_values("Sleep_Hours", ascending=False).head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Sleep_Stress_Ratio
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,2.250000
22356,U22357,36,Other,Professional,iOS,2.5,1.0,10,9.0,9,19,1,6.8,1.000000
22358,U22359,59,Male,Business Owner,Android,1.0,5.5,8,9.0,4,29,1,2.3,2.250000
48305,U48306,18,Other,Freelancer,Android,3.0,7.0,2,9.0,7,17,4,9.8,1.285714
25883,U25884,29,Male,Freelancer,Android,1.2,1.5,2,9.0,8,28,6,13.9,1.125000

In [16]:
stress.sort_values(["Occupation", "Sleep_Hours"], ascending=True).head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Sleep_Stress_Ratio
435,U436,57,Male,Business Owner,Android,4.9,3.5,7,4.0,6,18,3,5.5,0.666667
1967,U1968,43,Male,Business Owner,Android,9.3,2.7,6,4.0,7,35,6,10.4,0.571429
2466,U2467,52,Male,Business Owner,Android,3.0,5.0,10,4.0,2,9,4,10.6,2.000000
2616,U2617,21,Other,Business Owner,Android,5.6,2.1,2,4.0,9,57,6,11.6,0.444444
2705,U2706,58,Other,Business Owner,iOS,9.1,4.2,6,4.0,3,18,3,13.9,1.333333

## Lambda Functions in Python

A **lambda function** is a small, anonymous function defined in a single line.  
Lambda functions are useful when you need a **short function for a simple operation**, especially when working with pandas.

Python function:

```python
def square(x):
    return x**2
```

Corresponding Lambda function:

```python
lambda x: x**2
```

In [17]:
stress["Age"].apply(lambda x: x**2).head()

0    3364
1     625
2     361
3    1225
4    1089
Name: Age, dtype: int64

In [18]:
stress.apply(lambda row: row["Social_Media_Hours"] + row["Weekend_Screen_Time_Hours"], axis = 1).head()

0    15.4
1     6.6
2    12.0
3    15.3
4    11.2
dtype: float64

In [20]:
stress["Burnout_Risk"] = stress.apply(
    lambda row: "High"
    if row["Stress_Level"] > 7 and row["Sleep_Hours"] < 6
    else "Medium"
    if row["Stress_Level"] > 5
    else "Low",
    axis=1
)

## The `map()` Method in Pandas

The **`map()`** method is used to **transform the values in a single column (a pandas Series)**. It applies a function or mapping to **each individual value** in that column.

`map()` is commonly used to:
- Convert categorical values to numeric codes
- Replace values using a dictionary
- Apply simple transformations to each element

In [42]:
stress.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  str
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  str
 3   Occupation                 50000 non-null  str
 4   Device_Type                50000 non-null  str
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
 13  Sleep_Stress_Ratio         50000 non-null  float64
 14  Phone_Usage_Category       50000 non-null  str
dtypes: float64(5), int64(5), str(5)
memory usage: 5.7 MB

In [21]:
occupation_map = {
    "Professional": "P",
    "Student": "S",
    "Business Owner": "BO",
    "Freelancer": "F"
}

stress["Occupation_Short"] = stress["Occupation"].map(occupation_map)
stress[["Occupation", "Occupation_Short"]].head()

       Occupation Occupation_Short
0    Professional                P
1    Professional                P
2         Student                S
3  Business Owner               BO
4      Freelancer                F

## Writing Data with Pandas

After cleaning, transforming, or analyzing data, we often want to **save the results to a file**. Pandas makes it easy to write DataFrames to several common file formats.

The most common format for saving data is **CSV (Comma-Separated Values)**.

In [24]:
stress.to_csv("../data/smartphone_stress_v2.csv", index=False)

## Reading Data from a SQL Database with Pandas

Pandas can also load data directly from a **SQL database** using a SQL query.  
This allows you to retrieve only the data you need instead of loading an entire table.

The main function used for this is **`pd.read_sql()`**.

---

### Basic Syntax

```python
pd.read_sql(query, connection)

In [32]:
import sqlite3

conn = sqlite3.connect("../data/movies.sqlite")

movies = pd.read_sql("""
SELECT * FROM movies
""", conn)

directors = pd.read_sql("""
SELECT * FROM directors
""", conn)

movies.head()

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766

In [33]:
directors.head()

                name    id  gender   uid department
0      James Cameron  4762       2  2710  Directing
1     Gore Verbinski  4763       2  1704  Directing
2         Sam Mendes  4764       2    39  Directing
3  Christopher Nolan  4765       2   525  Directing
4     Andrew Stanton  4766       2     7  Directing

## Joining Data in Pandas

Often data is stored in **multiple tables**. To analyze it together, we need to **combine datasets based on a shared column**. In pandas, this is done using the **`merge()`** function.

This is similar to **SQL joins**.

---

### Basic Syntax

```python
pd.merge(left_df, right_df, on="column_name")

In [37]:
director_movies = pd.merge(directors, movies, left_on="id", right_on="director_id")
director_movies.head()

,name,id_x,gender,uid_x,department,id_y,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid_y,director_id
0,James Cameron,4762,2,2710,Directing,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,James Cameron,4762,2,2710,Directing,43622,Titanic,200000000,100,1997-11-18,1845034188,Titanic,7.5,7562,"84 years later, a 101-year-old woman named Ros...",Nothing on Earth could come between them.,597,4762
2,James Cameron,4762,2,2710,Directing,43876,Terminator 2: Judgment Day,100000000,101,1991-07-01,520000000,Terminator 2: Judgment Day,7.7,4185,Nearly 10 years have passed since Sarah Connor...,It's nothing personal.,280,4762
3,James Cameron,4762,2,2710,Directing,43879,True Lies,115000000,38,1994-07-14,378882411,True Lies,6.8,1116,Harry Tasker is a secret agent for the United ...,"When he said I do, he never said what he did.",36955,4762
4,James Cameron,4762,2,2710,Directing,44184,The Abyss,70000000,24,1989-08-09,90000098,The Abyss,7.1,808,A civilian oil rig crew is recruited to conduc...,There's everything you've ever known about adv...,2756,4762

## Working with Date and Time in Pandas

Many datasets include **date or time information**, such as timestamps, dates of events, or times of activity. Pandas provides powerful tools for converting and working with these values.

---

### Converting to Datetime

Dates are often stored as **strings** when data is first loaded.  
We can convert them to a proper datetime format using **`pd.to_datetime()`**.

```python
df["date"] = pd.to_datetime(df["date"])

In [48]:
director_movies["release_date"] = pd.to_datetime(director_movies["release_date"])
director_movies["release_date"].head()

0     Thursday
1      Tuesday
2       Monday
3     Thursday
4    Wednesday
Name: release_date, dtype: str

## Working with Dates in Pandas

Once a column has been converted to a **datetime type**, pandas provides convenient tools for extracting parts of the date and filtering data by time.

| Function | Description | Example |
|---|---|---|
| `.dt.year` | Extracts the year from a datetime value | `df["date"].dt.year` |
| `.dt.month` | Extracts the month (1–12) from a datetime value | `df["date"].dt.month` |
| `.dt.month_name()` | Returns the name of the month (e.g., January, February) | `df["date"].dt.month_name()` |
| `.dt.day` | Extracts the day of the month | `df["date"].dt.day` |
| `.dt.day_name()` | Returns the name of the day (e.g., Monday, Tuesday) | `df["date"].dt.day_name()` |
| Date filtering | Filters rows based on a date condition | `df[df["date"] > "2024-01-01"]` |

In [55]:
director_movies["Year"] = director_movies["release_date"].dt.year
director_movies["Month"] = director_movies["release_date"].dt.month_name()
director_movies["Day"] = director_movies["release_date"].dt.day_name()

director_movies[["title", "Year", "Month", "Day"]].head()

                        title  Year     Month        Day
0                      Avatar  2009  December   Thursday
1                     Titanic  1997  November    Tuesday
2  Terminator 2: Judgment Day  1991      July     Monday
3                   True Lies  1994      July   Thursday
4                   The Abyss  1989    August  Wednesday